services:
  biometric-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: biometric-app
    depends_on:
      - db
    ports:
      - "443:443"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/biometric_lab
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
  db:
    image: postgres:15
    container_name: biometric-lab-db
    networks:
      - app-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: biometric_lab
    ports:
      - "5432:5432"

networks:
  app-network:
    driver: bridge